import { StyleSheet } from 'react-native';
import { theme } from '../../../config/theme';

export const createStyles = (colors: any) =>
  StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: colors.background,
    },
    container: {
      flex: 1,
      paddingHorizontal: theme.spacing.lg,
      paddingTop: theme.spacing.md,
    },
    backButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      marginBottom: theme.spacing.sm,
    },
    backButtonText: {
      ...theme.typography.caption,
      fontWeight: '700',
      color: colors.primary,
    },
    title: {
      ...theme.typography.h1,
      marginBottom: theme.spacing.md,
      color: colors.text,
    },
    scrollContent: {
      paddingBottom: theme.spacing.xxl,
    },
    card: {
      padding: theme.spacing.md,
      borderRadius: theme.roundness.lg,
      borderWidth: 1,
      marginBottom: theme.spacing.lg,
      backgroundColor: colors.cardTranslucent,
      borderColor: colors.glassBorder,
    },
    cardTitle: {
      ...theme.typography.h2,
      fontSize: 18,
      marginBottom: theme.spacing.sm,
      color: colors.text,
    },
    fieldLabel: {
      ...theme.typography.caption,
      fontWeight: '700',
      textTransform: 'uppercase',
      fontSize: 10,
      marginBottom: theme.spacing.xs,
      color: colors.textSecondary,
    },
    freqScroll: {
      flexDirection: 'row',
      marginBottom: theme.spacing.sm,
    },
    freqChip: {
      paddingHorizontal: theme.spacing.md,
      paddingVertical: theme.spacing.sm,
      borderRadius: theme.roundness.full,
      borderWidth: 1,
      marginRight: theme.spacing.xs,
      borderColor: colors.border,
      backgroundColor: colors.background,
    },
    freqChipActive: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
    },
    freqChipText: {
      ...theme.typography.caption,
      fontWeight: '600',
      color: colors.text,
    },
    freqChipTextActive: {
      color: colors.white,
    },
    sectionHeaderTitle: {
      ...theme.typography.h2,
      fontSize: 18,
      marginBottom: 2,
      color: colors.text,
    },
    sectionSubTitle: {
      ...theme.typography.caption,
      marginBottom: theme.spacing.md,
      color: colors.textSecondary,
    },
    periodCard: {
      borderRadius: theme.roundness.lg,
      borderWidth: 1,
      padding: theme.spacing.md,
      marginBottom: theme.spacing.md,
      backgroundColor: colors.cardTranslucent,
      borderColor: colors.glassBorder,
    },
    periodCardHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      marginBottom: theme.spacing.sm,
    },
    periodTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: theme.spacing.sm,
    },
    iconBadge: {
      width: 40,
      height: 40,
      borderRadius: 20,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: colors.primary + '20',
    },
    periodCardTitle: {
      ...theme.typography.h2,
      fontSize: 16,
      color: colors.text,
    },
    tagBadge: {
      alignSelf: 'flex-start',
      paddingHorizontal: 8,
      paddingVertical: 2,
      borderRadius: theme.roundness.full,
      marginTop: 2,
      backgroundColor: colors.secondary + '20',
    },
    tagBadgeText: {
      ...theme.typography.caption,
      fontSize: 10,
      fontWeight: '700',
      color: colors.secondary,
    },
    deleteIconBtn: {
      padding: 4,
    },
    cardActionRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingTop: theme.spacing.sm,
      borderTopWidth: 1,
      borderTopColor: colors.border,
      marginTop: theme.spacing.xs,
    },
    cardActionText: {
      ...theme.typography.caption,
      fontWeight: '700',
      color: colors.primary,
    },

    /* Modal Styles */
    modalOverlay: {
      flex: 1,
      justifyContent: 'flex-end',
      backgroundColor: colors.overlay,
    },
    modalContainer: {
      borderTopLeftRadius: theme.roundness.lg,
      borderTopRightRadius: theme.roundness.lg,
      padding: theme.spacing.lg,
      maxHeight: '92%',
      borderWidth: 1,
      backgroundColor: colors.card,
      borderColor: colors.glassBorder,
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingBottom: theme.spacing.sm,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      marginBottom: theme.spacing.md,
    },
    modalTitle: {
      ...theme.typography.h2,
      fontSize: 18,
      color: colors.text,
    },
    modalSub: {
      ...theme.typography.caption,
      color: colors.textSecondary,
    },
    modalScrollContent: {
      paddingBottom: theme.spacing.xxl,
    },
    sectionTitle: {
      ...theme.typography.bodySemibold,
      fontSize: 15,
      marginBottom: theme.spacing.xs,
      color: colors.text,
    },
    systemToggleRow: {
      flexDirection: 'row',
      gap: 6,
      marginBottom: theme.spacing.md,
    },
    systemTab: {
      flex: 1,
      paddingVertical: 10,
      borderRadius: theme.roundness.sm,
      borderWidth: 1,
      justifyContent: 'center',
      alignItems: 'center',
      borderColor: colors.border,
      backgroundColor: colors.background,
    },
    systemTabActive: {
      backgroundColor: colors.primary + '20',
      borderColor: colors.primary,
    },
    systemTabText: {
      ...theme.typography.caption,
      fontSize: 11,
      fontWeight: '700',
      color: colors.text,
    },
    systemTabTextActive: {
      color: colors.primary,
    },

    /* Subject Card Styles */
    subjectCard: {
      borderRadius: theme.roundness.lg,
      borderWidth: 1,
      padding: theme.spacing.md,
      marginBottom: theme.spacing.md,
      backgroundColor: colors.background,
      borderColor: colors.border,
    },
    subjectCardHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: theme.spacing.sm,
    },
    iconBox: {
      width: 36,
      height: 36,
      borderRadius: 18,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: colors.secondary + '20',
    },
    subjectCardTitle: {
      ...theme.typography.bodySemibold,
      fontSize: 15,
      color: colors.text,
    },
    subjectBadgeRow: {
      flexDirection: 'row',
      gap: 6,
      marginTop: 2,
    },
    miniBadge: {
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: theme.roundness.full,
    },
    miniBadgeText: {
      ...theme.typography.caption,
      fontSize: 10,
      fontWeight: '700',
    },
    manageRewardsBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      paddingVertical: 10,
      borderRadius: theme.roundness.md,
      marginTop: theme.spacing.xs,
      backgroundColor: colors.secondary,
    },
    manageRewardsBtnText: {
      ...theme.typography.caption,
      color: '#ffffff',
      fontWeight: '700',
    },

    /* Rule Slot Card Styles */
    ruleSlotCard: {
      borderRadius: theme.roundness.lg,
      borderWidth: 1,
      padding: theme.spacing.md,
      marginBottom: theme.spacing.md,
      backgroundColor: colors.background,
      borderColor: colors.border,
    },
    ruleSlotHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: theme.spacing.xs,
    },
    ruleSlotTitle: {
      ...theme.typography.bodySemibold,
      fontSize: 14,
      color: colors.text,
    },
    ruleTypeRow: {
      flexDirection: 'row',
      gap: 6,
      marginBottom: theme.spacing.xs,
    },
    ruleTypeTab: {
      flex: 1,
      paddingVertical: 6,
      borderRadius: theme.roundness.sm,
      borderWidth: 1,
      alignItems: 'center',
      borderColor: colors.border,
      backgroundColor: colors.card,
    },
    ruleTypeTabText: {
      ...theme.typography.caption,
      fontSize: 11,
      fontWeight: '600',
      color: colors.textSecondary,
    },
    rangeInputsRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginBottom: theme.spacing.xs,
    },
    rangeInputSub: {
      ...theme.typography.caption,
      fontSize: 10,
      marginBottom: 2,
      color: colors.textSecondary,
    },
    rangeInput: {
      height: 38,
      borderWidth: 1,
      borderRadius: theme.roundness.sm,
      paddingHorizontal: 8,
      fontSize: 13,
      backgroundColor: colors.card,
      borderColor: colors.border,
      color: colors.text,
    },
    rangeToText: {
      ...theme.typography.caption,
      fontWeight: '700',
      marginTop: 14,
      color: colors.textSecondary,
    },
    rewardDescInput: {
      height: 42,
      borderWidth: 1,
      borderRadius: theme.roundness.md,
      paddingHorizontal: theme.spacing.md,
      fontSize: 13,
      backgroundColor: colors.card,
      borderColor: colors.border,
      color: colors.text,
    },
    addSlotBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      paddingVertical: 12,
      borderRadius: theme.roundness.lg,
      borderWidth: 1,
      borderStyle: 'dashed',
      marginBottom: theme.spacing.md,
      borderColor: colors.primary,
      backgroundColor: colors.primary + '10',
    },
    addSlotBtnText: {
      ...theme.typography.caption,
      fontWeight: '700',
      color: colors.primary,
    },
    chipRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      marginBottom: theme.spacing.sm,
    },
    chip: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: theme.spacing.md,
      paddingVertical: theme.spacing.sm,
      borderRadius: theme.roundness.full,
      borderWidth: 1,
      gap: 6,
      backgroundColor: colors.background,
      borderColor: colors.border,
    },
    chipActive: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
    },
    chipText: {
      ...theme.typography.caption,
      fontWeight: '600',
      color: colors.text,
    },
    chipTextActive: {
      color: colors.white,
    },
  });
